# Generated by Django 2.1 on 2019-08-21 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190821_1629'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atracao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100)),
                ('descricao', models.CharField(blank=True, max_length=700)),
                ('date', models.DateTimeField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'atracao',
                'verbose_name_plural': 'atracao',
            },
        ),
        migrations.RenameField(
            model_name='evento',
            old_name='date',
            new_name='enddate',
        ),
        migrations.AddField(
            model_name='evento',
            name='startdate',
            field=models.DateTimeField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='atracao',
            name='evento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='atracoes', to='core.Evento'),
        ),
    ]
