# Generated by Django 2.1 on 2018-08-21 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customauthentication', '0004_user_is_aluno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_aluno',
        ),
    ]
