# Generated by Django 2.1 on 2018-08-21 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customauthentication', '0005_remove_user_is_aluno'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_aluno',
            field=models.BooleanField(default=True),
        ),
    ]
