# Generated by Django 2.1 on 2018-09-05 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customauthentication', '0007_auto_20180821_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avaliador',
            field=models.BooleanField(default=True),
        ),
    ]
