# Generated by Django 2.1 on 2018-09-05 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customauthentication', '0008_user_avaliador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avaliador',
            field=models.BooleanField(default=False),
        ),
    ]
