# Generated by Django 2.1 on 2019-01-10 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customauthentication', '0009_auto_20180905_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cpf',
            field=models.CharField(default=1, max_length=255, unique=True, verbose_name='cpf'),
            preserve_default=False,
        ),
    ]
