# Generated by Django 2.1.7 on 2019-03-28 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customauthentication', '0010_user_cpf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_comum',
        ),
    ]
